name: Matt Davidson
favicon: null
layout_spectrum: 1
typography_spectrum: 0.31197
title: 'Matt Davidson '
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ff9900'
    - '#424242'
    - '#bcbcbc'
    - '#3299bb'
    - '#737373'
  brandStrength: 0.8125
  lightness: 0.25
  saturation: 1
  rhythmicContrast: 0.4234042
purpose: []
