name: Matt Davidson
favicon: null
layout_spectrum: 0.938993263291195
typography_spectrum: 0.0007009045220911503
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.6385533416178077
  lightness: 0.05317387776449323
  saturation: 0.6797118734102696
  rhythmicContrast: 0.055364393163472414
purpose: []
