name: Matt Davidson
favicon: null
layout_spectrum: 1
typography_spectrum: 0.49086
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#312819'
    - '#626554'
    - '#fefdff'
    - '#94becc'
    - '#a48779'
  brandStrength: 0.6385533416178077
  lightness: 0.05317387776449323
  saturation: 0.6797118734102696
  rhythmicContrast: 0.055364393163472414
purpose: []
