name: Matt Davidson
favicon: null
layout_spectrum: 1
typography_spectrum: 0.30303
title: 'Matt Davidson '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ff9900'
    - '#424242'
    - '#bcbcbc'
    - '#3299bb'
    - '#737373'
  brandStrength: 0.6385533416178077
  lightness: 0.375
  saturation: 0.6797118734102696
  rhythmicContrast: 0.055364393163472414
purpose: []
